
export const Environment = {
    BACKEND_API_PROTOCOL: process.env.REACT_APP_BACKEND_API_PROTOCOL,
    BACKEND_API_HOST: process.env.REACT_APP_BACKEND_API_HOST,
    BACKEND_API_PORT: process.env.REACT_APP_BACKEND_API_PORT,
    BACKEND_API_BASE_URL: process.env.REACT_APP_BACKEND_API_PROTOCOL + "://" +
        process.env.REACT_APP_BACKEND_API_HOST +
        (process.env.REACT_APP_BACKEND_API_PORT ? ":" + process.env.REACT_APP_BACKEND_API_PORT : ""),
    OAUTH_LOGIN_REDIRECT_URL: process.env.REACT_APP_OAUTH_LOGIN_REDIRECT_URL,
    SOCKET_PROTOCOL: process.env.REACT_APP_SOCKET_PROTOCOL
}: